import { beforeEach, describe, expect, it } from 'vitest';
import {
  addBehaviorEvent,
  addIncident,
  addSessionNote,
  addSkillTrial,
  db,
  getUnsyncedBehaviorEvents,
  getUnsyncedIncidents,
  getUnsyncedSessionNotes,
  getUnsyncedSkillTrials,
  updateBehaviorEventIntervention,
} from './db';
import { useEncryptionStore } from '../stores/encryptionStore';

describe('db encrypted flow', () => {
  beforeEach(async () => {
    await useEncryptionStore.getState().initializeWithPassword('TestPass123!', 'U3RhdGljU2FsdDEyMw==');
    await db.behaviorEvents.clear();
    await db.skillTrials.clear();
    await db.sessionNotes.clear();
    await db.incidents.clear();
  });

  it('stores and retrieves all PHI entity types through encrypted paths', async () => {
    const now = new Date();

    await addBehaviorEvent({
      sessionId: 1,
      behaviorType: 'elopement',
      count: 1,
      duration: 45,
      antecedent: 'work demand',
      consequent: 'redirect',
      functionGuess: 'escape',
      intervention: 'FCR',
      intensity: 2,
      notes: 'returned in under one minute',
      timestamp: now,
      createdAt: now,
      synced: false,
    });

    await addSkillTrial({
      sessionId: 1,
      skillName: 'Imitation',
      target: 'clap hands',
      promptLevel: 'gestural',
      response: 'correct',
      reinforcementDelivered: true,
      reinforcementType: 'praise',
      notes: 'needed one prompt',
      timestamp: now,
      createdAt: now,
      synced: false,
    });

    await addSessionNote({
      sessionId: 1,
      section: 'summary',
      content: 'Strong participation with one elopement event.',
      isAutoGenerated: true,
      editHistory: [],
      createdAt: now,
      updatedAt: now,
      synced: false,
    });

    await addIncident({
      sessionId: 1,
      incidentType: 'injury',
      description: 'minor scratch during transition',
      staffInvolved: ['RBT A'],
      actionsToken: ['First aid', 'Called supervisor'],
      injuries: 'left forearm scratch',
      parentNotified: true,
      supervisorNotified: true,
      timestamp: now,
      createdAt: now,
      synced: false,
    });

    const [behaviors, skills, notes, incidents] = await Promise.all([
      getUnsyncedBehaviorEvents(),
      getUnsyncedSkillTrials(),
      getUnsyncedSessionNotes(),
      getUnsyncedIncidents(),
    ]);

    expect(behaviors).toHaveLength(1);
    expect(behaviors[0].behaviorType).toBe('elopement');

    expect(skills).toHaveLength(1);
    expect(skills[0].skillName).toBe('Imitation');

    expect(notes).toHaveLength(1);
    expect(notes[0].content).toContain('Strong participation');

    expect(incidents).toHaveLength(1);
    expect(incidents[0].incidentType).toBe('injury');

    const [rawBehavior, rawSkill, rawNote, rawIncident] = await Promise.all([
      db.behaviorEvents.toCollection().first(),
      db.skillTrials.toCollection().first(),
      db.sessionNotes.toCollection().first(),
      db.incidents.toCollection().first(),
    ]);

    expect(rawBehavior?.encryptedData).toBeDefined();
    expect(rawBehavior?.encryptedData.ciphertext).toBeTypeOf('string');
    expect(rawBehavior?.signature).toBeTypeOf('string');

    expect(rawSkill?.encryptedData.ciphertext).toBeTypeOf('string');
    expect(rawNote?.encryptedData.ciphertext).toBeTypeOf('string');
    expect(rawIncident?.encryptedData.ciphertext).toBeTypeOf('string');
  });

  it('updates intervention on encrypted behavior events', async () => {
    const now = new Date();
    const behaviorId = await addBehaviorEvent({
      sessionId: 1,
      behaviorType: 'tantrum',
      duration: 30,
      timestamp: now,
      createdAt: now,
      synced: false,
    });

    await updateBehaviorEventIntervention(behaviorId, 'Redirect');
    const behaviors = await getUnsyncedBehaviorEvents();

    expect(behaviors).toHaveLength(1);
    expect(behaviors[0].intervention).toBe('Redirect');
  });
});
