import Dexie, { type EntityTable } from 'dexie';

// Types for our data models
export interface Session {
    id?: number;
    clientId: string;
    clientName: string;
    startTime: Date;
    endTime?: Date;
    status: 'in-progress' | 'completed';
    location?: string;
    createdAt: Date;
    updatedAt: Date;
}

export interface BehaviorEvent {
    id?: number;
    sessionId: number;
    behaviorType: string; // e.g., 'elopement', 'tantrum', 'aggression', 'SIB'
    count?: number;
    duration?: number; // in seconds
    antecedent?: string;
    consequent?: string;
    functionGuess?: 'escape' | 'tangible' | 'attention' | 'automatic' | 'unsure';
    intervention?: string;
    intensity?: 1 | 2 | 3; // Low, Moderate, High
    notes?: string;
    timestamp: Date;
    createdAt: Date;
    synced: boolean;
}

export interface SkillTrial {
    id?: number;
    sessionId: number;
    skillName: string;
    target: string;
    promptLevel: 'independent' | 'verbal' | 'gestural' | 'model' | 'partial-physical' | 'full-physical';
    response: 'correct' | 'incorrect' | 'no-response' | 'prompted';
    reinforcementDelivered: boolean;
    reinforcementType?: string;
    notes?: string;
    timestamp: Date;
    createdAt: Date;
    synced: boolean;
}

export interface SessionNote {
    id?: number;
    sessionId: number;
    section: string; // e.g., 'summary', 'behaviors', 'skills', 'recommendations'
    content: string;
    isAutoGenerated: boolean;
    editHistory: { timestamp: Date; previousContent: string; editedBy: string }[];
    createdAt: Date;
    updatedAt: Date;
    synced: boolean;
}

export interface Incident {
    id?: number;
    sessionId: number;
    incidentType: 'injury' | 'restraint' | 'property-destruction' | 'elopement-serious' | 'other';
    description: string;
    staffInvolved: string[];
    actionsToken: string[];
    witnesses?: string[];
    injuries?: string;
    parentNotified: boolean;
    supervisorNotified: boolean;
    timestamp: Date;
    createdAt: Date;
    synced: boolean;
}

export interface SyncQueueItem {
    id?: number;
    entityType: 'behavior' | 'skillTrial' | 'note' | 'incident' | 'session';
    entityId: number;
    action: 'create' | 'update' | 'delete';
    payload: string; // JSON stringified data
    attempts: number;
    lastAttempt?: Date;
    createdAt: Date;
}

export interface ChatMessage {
    id?: number;
    sessionId: number;
    role: 'user' | 'assistant' | 'system';
    content: string;
    buttons?: { label: string; action: string; value: string }[];
    isConfirmation: boolean;
    timestamp: Date;
}

// Create the database
class SessionCoPilotDB extends Dexie {
    sessions!: EntityTable<Session, 'id'>;
    behaviorEvents!: EntityTable<BehaviorEvent, 'id'>;
    skillTrials!: EntityTable<SkillTrial, 'id'>;
    sessionNotes!: EntityTable<SessionNote, 'id'>;
    incidents!: EntityTable<Incident, 'id'>;
    syncQueue!: EntityTable<SyncQueueItem, 'id'>;
    chatMessages!: EntityTable<ChatMessage, 'id'>;

    constructor() {
        super('SessionCoPilotDB');

        this.version(1).stores({
            sessions: '++id, clientId, status, startTime',
            behaviorEvents: '++id, sessionId, behaviorType, synced, timestamp',
            skillTrials: '++id, sessionId, skillName, synced, timestamp',
            sessionNotes: '++id, sessionId, section, synced',
            incidents: '++id, sessionId, incidentType, synced, timestamp',
            syncQueue: '++id, entityType, entityId, action, createdAt',
            chatMessages: '++id, sessionId, role, timestamp'
        });
    }
}

export const db = new SessionCoPilotDB();

// Helper functions
export async function addToSyncQueue(
    entityType: SyncQueueItem['entityType'],
    entityId: number,
    action: SyncQueueItem['action'],
    payload: object
) {
    await db.syncQueue.add({
        entityType,
        entityId,
        action,
        payload: JSON.stringify(payload),
        attempts: 0,
        createdAt: new Date()
    });
}

export async function getUnsyncedCount(): Promise<number> {
    const behaviors = await db.behaviorEvents.where('synced').equals(0).count();
    const trials = await db.skillTrials.where('synced').equals(0).count();
    const notes = await db.sessionNotes.where('synced').equals(0).count();
    const incidents = await db.incidents.where('synced').equals(0).count();
    return behaviors + trials + notes + incidents;
}
